# Generated by Django 3.2.13 on 2022-10-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='team',
            field=models.BooleanField(default=False),
        ),
    ]
